#!/bin/bash
(
cat << EOF
From: Peter Jones <pjones@redhat.com>" 
Date: $(date)
Subject: [PATCH] Changes from grub-0.97 to fedora-17

This patch is a bundle of the changes between grub-0.97 and fedora-17.
It can be reginerated from the git repository at:

git://github.com/vathpela/grub-fedora.git

Using the command:

git diff grub-0.97 fedora-17

EOF
git diff grub-0.97 fedora-17 | diffstat -p1
echo
git diff grub-0.97 fedora-17
) | cat
